### ISSUE TITLE
when to release the code

### ISSUE THREAD

**Issue by VoyageWang** [Dmmm1997/SimVG#1]
Hi, when will the code be released? The training computational resources you used are a single 3090 GPU or 8 GPUs, which is not clearly stated in your paper. Thanks for your great work!

**Comment by Dmmm1997** [comment]
Thank you for your attention to our work. 
The code is being sorted out.

Pre-training requires 8 RTX3090 to train for about 1 day.  A single dataset such as refcoco/+/g only requires one RTX3090 to train for about half a day.
